### ISSUE TITLE
bin/windows/genie vs2017 fails

### ISSUE THREAD

**Issue by KhardanOne** [hugoam/two#24]
It seems that genie wants to write outside two's folder. It fails. Following the README.md on Win10 character by character I got:

```
c:\Learning\Code\CPP\TWOROOT\two>bin/windows/genie vs2017
'bin' is not recognized as an internal or external command, operable program or batch file.
```

Tried with backslashes instead of fwd slashes:

```
c:\Learning\Code\CPP\TWOROOT\two>bin\windows\genie.exe vs2017
setting windowsTargetPlatformVersion to 8.1
cannot open c:/Learning/Code/CPP/TWOROOT/bx/scripts/bx.lua: No such file or directory
stack traceback:
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:96: in function 'dofile'
        c:/Learning/Code/CPP/TWOROOT/two/scripts/3rdparty/bgfx/bgfx.lua:6: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:96: in function 'dofile'
        c:/Learning/Code/CPP/TWOROOT/two/scripts/two.lua:33: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:96: in function 'dofile'
        c:/Learning/Code/CPP/TWOROOT/two/scripts/genie.lua:21: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:96: in function 'dofile'
        [string "_WORKING_DIR        = os.getcwd()..."]:45: in function '_premake_main'
```

Tried with quotes and forward slashes (`"bin/windows/genie.exe" vs2017`) with the same results.

Tried on another drive and as an admin to make sure it is not a rights issue. Same results.

It would be useful to mention in the README.md to put two inside an extra new folder as it will write things its parent dir.

**Comment by hugoam** [comment]
The installation instructions have changed, sorry about that
`bx`, `bimg` and `bgfx` must now be cloned outside of `two`'s repository
You can have a look at the updated build instructions https://github.com/hugoam/two#building
Also as a general rule of thumb, it helps to see what the CI script is doing (https://github.com/hugoam/two/blob/master/.travis.yml#L14) to understand how the lib is to be built, since as long as the CI build is green, it means it's succeeding to build the whole thing :)
